@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTUzMzc4ODF9.rgx4nmzPZQS-K3M5AmPEzUpR6JoTCFoBlbnb4y_gE6g
@host = http://localhost:3000

### Products Index
Get {{host}}/products.json

### Show Product
GET {{host}}/products/2.json

### Product Create
POST {{host}}/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Lawn Chair",
  "price": 25,
  "image_url": "https://m.media-amazon.com/images/I/71X8adLx6oL._AC_UL320_.jpg",
  "description": "Coleman Mesh Quad Camping Chair, Red"
}

### Product Update
PATCH {{host}}/products/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "price": 10,
  "supplier_id": 2
}

### Supplier Index
Get {{host}}/suppliers.json

### Show Supplier
Get {{host}}/suppliers/2.json

### Image Index
Get {{host}}/images.json

### Show Image
Get {{host}}/images/3.json

### Create an Image
Post {{host}}/images.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "url": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/bca8639ba25a427aac93ab8401878390_9366/Athletic_Cushioned_Quarter_Socks_6_Pairs_XL_Black_B93227_03_standard.jpg",
  "product_id": 3
}

### Create a User (signup)
Post {{host}}/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{host}}/sessions.json
Content-Type: application/json

{
  "email": "kevin@test.com",
  "password": "password"
}

### Create an Order
post {{host}}/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
}

### Update an Order
patch {{host}}/orders/1.json
Content-Type: application/json

{
  "quantity": 3
}

### Show an Order
Get {{host}}/orders/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Index all Orders
Get {{host}}/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Carted_Product Create
POST {{host}}/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 4,
  "quantity": 5
}

### Index all CartedProducts
Get {{host}}/carted_products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Update a CartedProduct 
patch {{host}}/carted_products/3.json
Content-Type: application/json

{
  "status": "removed"
}

### Delete CartedProducts
delete {{host}}/carted_products/14.json
Authorization: Bearer {{jwt}}
Content-Type: application/json