@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI4MzEyMTR9.VYhCNOROHNrrllTb0XKX1mh_rgkI_AH-A32lweeLfWo

### Products Index
Get http://localhost:3000/products.json

### Show Product
GET http://localhost:3000/products/2.json

### Product Create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Lawn Chair",
  "price": 25,
  "image_url": "https://m.media-amazon.com/images/I/71X8adLx6oL._AC_UL320_.jpg",
  "description": "Coleman Mesh Quad Camping Chair, Red"
}

### Product Update
PATCH http://localhost:3000/products/2.json
Content-Type: application/json

{
  "price": 9,
  "supplier_id": 2
}

### Supplier Index
Get http://localhost:3000/suppliers.json

### Show Supplier
Get http://localhost:3000/suppliers/2.json

### Image Index
Get http://localhost:3000/images.json

### Show Image
Get http://localhost:3000/images/3.json

### Create an Image
Post http://localhost:3000/images.json
Content-Type: application/json

{
  "url": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/bca8639ba25a427aac93ab8401878390_9366/Athletic_Cushioned_Quarter_Socks_6_Pairs_XL_Black_B93227_03_standard.jpg",
  "product_id": 3
}

### Create a User (signup)
Post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "kevin",
  "email": "kevin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Create an Order
post http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 3
}

### Update an Order
patch http://localhost:3000/orders/1.json
Content-Type: application/json

{
  "quantity": 3,
  "subtotal": 60,
  "tax": 5.4,
  "total": 65.4
}

### Show an Order
Get http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Index all Orders
Get http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json